const $=id=>document.getElementById(id),AR=['٠','١','٢','٣','٤','٥','٦','٧','٨','٩'];
const toAr=n=>String(n).replace(/\d/g,d=>AR[d]);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const SURAH_NAMES=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const PAGE_STARTS=[1,2,50,77,106,128,151,177,187,208,221,235,249,255,262,267,282,293,305,312,322,332,342,350,359,367,377,385,396,404,411,415,418,428,434,440,446,453,458,467,477,483,489,496,499,502,507,511,515,518,520,523,526,528,531,534,537,542,545,549,551,553,554,556,558,560,562,564,566,568,570,572,574,575,577,578,580,582,583,585,586,587,587,589,590,591,591,592,593,594,595,595,596,596,597,597,598,598,599,599,600,600,601,601,601,602,602,602,603,603,603,604,604,604];
const JUZ_PAGE_STARTS=[1,22,42,62,82,102,121,142,162,182,201,222,242,262,282,302,322,342,362,382,402,422,442,462,482,502,522,542,562,582];
const META=Object.fromEntries(SURAH_NAMES.map((name,i)=>[i+1,{name,pages:[PAGE_STARTS[i],i===113?604:PAGE_STARTS[i+1]]}]));
const FALLBACK_FATIHA=['بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ','ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ','ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ','مَـٰلِكِ يَوْمِ ٱلدِّينِ','إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ','ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ','صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ'];
const state={surah:Number(localStorage.getItem('basair-v3-surah')||1),page:Number(localStorage.getItem('basair-v3-page')||1),verse:null,open:null,markers:localStorage.getItem('basair-v3-markers')!=='off',downloading:false,zoom:Number(localStorage.getItem('basair-page-width')||780)};
const pageFonts=new Map(),pageMemory=new Map(),fontMemory=new Map(),questionIndex=new Map();
for(const q of window.BASAIR_QUESTIONS||[])for(const verse of q.verses||[]){const key=`${q.surah}:${verse}`;if(!questionIndex.has(key))questionIndex.set(key,[]);questionIndex.get(key).push(q)}

const DB_NAME='basair-mushaf-offline-v5';
const QPC_BASE='https://cdn.jsdelivr.net/gh/hussainsajib/qpc-v4-mushaf-bundle@f84ccb5688d5404748a0d38e6c53e09df4469ec9';
let qpcDataPromise=null,qpcWords=null,qpcCodes=null;
const dbPromise=new Promise(resolve=>{if(!('indexedDB'in window)){resolve(null);return}const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('pages'))db.createObjectStore('pages');if(!db.objectStoreNames.contains('fonts'))db.createObjectStore('fonts')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(null)});
async function dbGet(store,key){const db=await dbPromise;if(!db)return null;return new Promise(resolve=>{const tx=db.transaction(store,'readonly'),r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>resolve(null)})}
async function dbPut(store,key,value){const db=await dbPromise;if(!db)return false;return new Promise(resolve=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false)})}

function questionsFor(surah,verse){return questionIndex.get(`${surah}:${verse}`)||[]}
function sourcesHtml(items){return(items||[]).map(x=>x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`:`<span>${esc(x.label)}</span>`).join(' · ')}
function normalizeArabic(text){return String(text||'').replace(/<[^>]*>/g,'').replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[^\u0621-\u063A\u0641-\u064A\s]/g,' ').replace(/\s+/g,' ').trim()}
function cleanVerseText(text){return String(text||'').replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim()}
function normalizedTextMap(original){let normalized='',map=[];for(let i=0;i<original.length;i++){let char=original[i];if(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED\u0640]/.test(char))continue;char=char.replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه');if(/[\u0621-\u063A\u0641-\u064A]/.test(char)){normalized+=char;map.push(i)}else if(normalized&&!normalized.endsWith(' ')){normalized+=' ';map.push(i)}}while(normalized.endsWith(' ')){normalized=normalized.slice(0,-1);map.pop()}return{normalized,map}}
function highlightedVerse(text,query){const original=cleanVerseText(text),needle=normalizeArabic(query);if(!needle)return esc(original);const{normalized,map}=normalizedTextMap(original),start=normalized.indexOf(needle);if(start<0)return esc(original);const from=map[start];let to=(map[start+needle.length-1]??from)+1;while(to<original.length&&/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/.test(original[to]))to++;return `${esc(original.slice(0,from))}<mark>${esc(original.slice(from,to))}</mark>${esc(original.slice(to))}`}
function populateSurahs(){$('surahSelect').innerHTML=SURAH_NAMES.map((name,i)=>`<option value="${i+1}">${toAr(i+1)} · سورة ${name}</option>`).join('')}
function pageWithinSurah(surah,page){const range=META[surah].pages;return page>=range[0]&&page<=range[1]}
const spreadQuery=matchMedia('(orientation:landscape) and (min-width:900px)');
function spreadMode(){return spreadQuery.matches}
function spreadStart(page){page=Math.max(1,Math.min(604,Number(page)||1));return spreadMode()&&page%2===0?page-1:page}
function updateChrome(){state.page=spreadStart(state.page);const meta=META[state.surah]||META[1],second=spreadMode()&&state.page<604;$('surahSelect').value=state.surah;$('readerTitle').textContent=`سورة ${meta.name}`;$('pageJumpBtn').textContent=second?`الصفحتان ${toAr(state.page)}–${toAr(state.page+1)} من ${toAr(604)}`:`الصفحة ${toAr(state.page)} من ${toAr(604)}`;$('pageNumber').textContent=toAr(state.page);$('footerSurah').textContent=meta.name;$('surahLabel').textContent=`سورة ${meta.name}`;$('prevPage').disabled=state.page<=1;$('nextPage').disabled=second?state.page>=603:state.page>=604;$('edgePrev').disabled=state.page<=1;$('edgeNext').disabled=second?state.page>=603:state.page>=604;$('edgeNextSecond').disabled=state.page>=603;$('mushaf').classList.toggle('page-one',state.page===1);$('mushaf').classList.toggle('opening-page',state.page<=2);document.body.classList.toggle('spread-mode',spreadMode());document.body.classList.toggle('hide-markers',!state.markers);$('markersBtn').classList.toggle('active',state.markers);$('markersBtn').setAttribute('aria-pressed',String(state.markers));localStorage.setItem('basair-v3-page',state.page);localStorage.setItem('basair-v3-surah',state.surah)}

async function getFontBytes(page){if(fontMemory.has(page))return fontMemory.get(page);const cached=await dbGet('fonts',page);if(cached){fontMemory.set(page,cached);return cached}const response=await fetch(`${QPC_BASE}/fonts/qpcv4/p${page}.woff2`);if(!response.ok)throw new Error('font-network');const bytes=await response.arrayBuffer();fontMemory.set(page,bytes);await dbPut('fonts',page,bytes);return bytes}
async function loadFont(page){const name=`qcf-p${page}`;if(pageFonts.has(page))return pageFonts.get(page);const pending=(async()=>{const bytes=await getFontBytes(page),face=new FontFace(name,bytes,{style:'normal',weight:'400',display:'block'});await face.load();if(face.status!=='loaded')throw new Error('font');document.fonts.add(face);await document.fonts.ready;return name})();pageFonts.set(page,pending);try{return await pending}catch(error){pageFonts.delete(page);throw error}}
async function fetchQpcText(path){const response=await fetch(`${QPC_BASE}/data/${path}`);if(!response.ok)throw new Error('qpc-data-network');return response.text()}
async function loadQpcData(){
  if(qpcDataPromise)return qpcDataPromise;
  qpcDataPromise=(async()=>{
    const[wordsCsv,mappingCsv]=await Promise.all([fetchQpcText('words.csv'),fetchQpcText('qpc_mapping.csv')]);
    qpcWords=new Map();qpcCodes=new Map();
    const wordRows=wordsCsv.trim().split(/\r?\n/);
    for(let i=1;i<wordRows.length;i++){const r=wordRows[i].split(','),id=Number(r[0]);qpcWords.set(id,{id,text:r.slice(5).join(','),surah:Number(r[2]),ayah:Number(r[3]),word:Number(r[4])})}
    const codeRows=mappingCsv.trim().split(/\r?\n/);
    for(let i=1;i<codeRows.length;i++){const r=codeRows[i].split(','),id=Number(r[0]);qpcCodes.set(id,(r[2]||'').trim().split(/\s+/).filter(Boolean).map(Number))}
    if(qpcWords.size!==83668||qpcCodes.size!==83668)throw new Error('qpc-data-incomplete');
  })();
  try{await qpcDataPromise}catch(error){qpcDataPromise=null;qpcWords=null;qpcCodes=null;throw error}
}
function juzForPageNumber(page){let juz=1;for(let i=0;i<JUZ_PAGE_STARTS.length;i++)if(JUZ_PAGE_STARTS[i]<=page)juz=i+1;return juz}
function buildQpcPage(page){
  const layout=window.BASAIR_PAGE_LINES?.[page]||[],verses=new Map(),juz=juzForPageNumber(page);
  for(const[line,type,,first,last]of layout){
    if(type!=='ayah')continue;
    for(let id=first;id<=last;id++){
      const source=qpcWords.get(id),codes=qpcCodes.get(id);if(!source||!codes?.length)throw new Error(`qpc-word-${id}`);
      const key=`${source.surah}:${source.ayah}`,verse=verses.get(key)||{id,verse_key:key,verse_number:source.ayah,juz_number:juz,hizb_number:juz*2-1,words:[]};
      verse.words.push({id,line_number:line,page_number:page,code_v2:String.fromCodePoint(...codes),text_qpc_hafs:source.text,text:source.text,char_type_name:/^\p{Nd}+$/u.test(source.text)?'end':'word'});
      verses.set(key,verse);
    }
  }
  return{verses:[...verses.values()],pagination:{current_page:1,next_page:null},source:'qpc-v4'};
}
async function fetchPage(page){
  if(pageMemory.has(page))return pageMemory.get(page);
  const cached=await dbGet('pages',page);if(cached?.source==='qpc-v4'&&cached.verses?.length){pageMemory.set(page,cached);return cached}
  await loadQpcData();const data=buildQpcPage(page);
  pageMemory.set(page,data);await dbPut('pages',page,data);return data;
}

function verseTextFromData(verse){return(verse.words||[]).filter(w=>w.char_type_name!=='end').map(w=>w.text_qpc_hafs||w.text||'').join(' ').replace(/\s+/g,' ').trim()}
async function searchDownloadedPages(query,limit=50){const needle=normalizeArabic(query),results=[];if(!needle)return results;for(let page=1;page<=604&&results.length<limit;page++){const data=pageMemory.get(page)||await dbGet('pages',page);if(!data?.verses)continue;for(const verse of data.verses){const text=verseTextFromData(verse);if(normalizeArabic(text).includes(needle)){results.push({verse_key:verse.verse_key,text,page_number:page});if(results.length>=limit)break}}}return results}
async function searchQuran(query){const url=`https://api.quran.com/api/v4/search?q=${encodeURIComponent(query)}&size=50&page=0&language=ar`;try{const response=await fetch(url);if(!response.ok)throw new Error('search-network');const data=await response.json(),items=data.search?.results||[];return{items:items.map(item=>({verse_key:item.verse_key,text:cleanVerseText(item.text),page_number:item.page_number||null})),total:data.search?.total_results??items.length,online:true}}catch{const items=await searchDownloadedPages(query);return{items,total:items.length,online:false}}}
async function pageForVerse(verseKey,knownPage){if(knownPage)return Number(knownPage);for(const[page,data]of pageMemory)if(data.verses?.some(v=>v.verse_key===verseKey))return page;const response=await fetch(`https://api.quran.com/api/v4/verses/by_key/${verseKey}?fields=page_number&words=false&mushaf=1`);if(!response.ok)throw new Error('verse-page');const data=await response.json();return Number(data.verse?.page_number)}
function openQuranSearch(){$('quranSearchOverlay').classList.add('open');$('quranSearchOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('quranSearchInput').focus(),50)}
function closeQuranSearch(){$('quranSearchOverlay').classList.remove('open');$('quranSearchOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderSearchResults(items,total,query,online){$('quranSearchResults').innerHTML=items.length?`<div class="search-summary">${toAr(total)} نتيجة${total>items.length?` · تظهر أول ${toAr(items.length)}`:''}${online?'':' · من الصفحات المحفوظة على الجهاز'}</div>`+items.map(item=>{const[surah,verse]=item.verse_key.split(':').map(Number),count=questionsFor(surah,verse).length;return `<button class="verse-result" data-key="${item.verse_key}" data-page="${item.page_number||''}"><span class="verse-result-meta"><span>سورة ${SURAH_NAMES[surah-1]} · الآية ${toAr(verse)}</span>${count?`<span class="verse-result-count">${toAr(count)} ${count===1?'بصيرة':'بصائر'}</span>`:''}</span><span class="verse-result-text">${highlightedVerse(item.text,query)}</span></button>`}).join(''):`<div class="search-error">لم نجد آيات مطابقة.<br><small>${online?'جرّب كلمة أخرى أو احذف بعض الكلمات.':'نزّل المصحف أولًا ليعمل البحث دون اتصال.'}</small></div>`;document.querySelectorAll('.verse-result').forEach(button=>button.addEventListener('click',()=>goToSearchResult(button.dataset.key,button.dataset.page)))}
let searchTimer=0,searchRequest=0;async function performQuranSearch(){const query=$('quranSearchInput').value.trim(),request=++searchRequest;if(normalizeArabic(query).length<2){$('quranSearchResults').innerHTML='<div class="search-welcome"><b>⌕</b><span>اكتب كلمة أو جزءًا من الآية لتظهر النتائج.</span></div>';return}$('quranSearchResults').innerHTML='<div class="search-loader"></div><div class="search-summary" style="text-align:center">جارٍ البحث…</div>';const result=await searchQuran(query);if(request!==searchRequest)return;renderSearchResults(result.items,result.total,query,result.online)}
async function goToSearchResult(verseKey,knownPage){const[surah,verse]=verseKey.split(':').map(Number);try{const page=await pageForVerse(verseKey,knownPage);if(!page)throw new Error('page');closeQuranSearch();state.surah=surah;state.page=page;await loadPage();selectVerse(surah,verse,false);document.querySelector(`.word[data-surah="${surah}"][data-verse="${verse}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});toast(`سورة ${SURAH_NAMES[surah-1]} · الآية ${toAr(verse)}`)}catch{toast('تعذر فتح الآية؛ تحقق من الاتصال بالإنترنت',3000)}}

function marker(surah,verse){const count=questionsFor(surah,verse).length;return count?`<button class="marker" data-marker-surah="${surah}" data-marker-verse="${verse}" aria-label="${toAr(count)} أسئلة للآية ${toAr(verse)}">${toAr(count)}</button>`:''}
function selectVerse(surah,verse,reveal=true){state.surah=surah;state.verse=verse;state.open=null;$('surahSelect').value=surah;$('search').value='';document.querySelectorAll('.word').forEach(w=>w.classList.toggle('selected',Number(w.dataset.surah)===surah&&Number(w.dataset.verse)===verse));renderQuestions();if(reveal){$('panel').classList.add('open');$('backdrop').classList.add('open')}}
let suppressClickUntil=0;function bindPage(root=document){root.querySelectorAll('.word').forEach(w=>w.addEventListener('click',e=>{if(Date.now()<suppressClickUntil)return;if(!e.target.closest('.marker'))selectVerse(Number(w.dataset.surah),Number(w.dataset.verse))}));root.querySelectorAll('.marker').forEach(m=>m.addEventListener('click',e=>{e.stopPropagation();if(Date.now()<suppressClickUntil)return;selectVerse(Number(m.dataset.markerSurah),Number(m.dataset.markerVerse))}))}
function animateMushafBody(body=$('mushafBody')){body.classList.remove('page-enter');requestAnimationFrame(()=>body.classList.add('page-enter'))}
let lineFitFrame=0,lineFitResizeTimer=0;
function fitOnePage(root){if(!root||getComputedStyle(root).display==='none')return;const lines=[...root.querySelectorAll('.mushaf-line')];if(!lines.length)return;lines.forEach(line=>{line.style.fontSize='';line.style.justifyContent='center'});for(const line of lines){const words=[...line.children].filter(el=>el.classList.contains('word')),available=line.clientWidth-8,natural=words.reduce((sum,word)=>sum+word.getBoundingClientRect().width,0);if(!available||!natural)continue;const base=parseFloat(getComputedStyle(line).fontSize);if(natural>available){line.style.fontSize=`${base*(available/natural)}px`;continue}const gap=words.length>1?(available-natural)/(words.length-1):Infinity;if(!line.classList.contains('centered')&&gap<=base)line.style.justifyContent='space-between'}}
function fitMushafLines(){cancelAnimationFrame(lineFitFrame);lineFitFrame=requestAnimationFrame(()=>{fitOnePage($('mushaf'));fitOnePage($('mushafSecond'))})}
function pageHtml(data,font,useGlyphs=true,page=state.page){
  const fallbackLines=new Map();
  for(const v of data.verses||[]){
    const surah=Number(String(v.verse_key).split(':')[0]),verse=Number(v.verse_number),verseWords=v.words||[];
    for(const w of verseWords){
      const line=Math.max(1,Math.min(15,Number(w.line_number)||1));
      const enriched={...w,verse,surah};
      if(!fallbackLines.has(line))fallbackLines.set(line,[]);fallbackLines.get(line).push(enriched);
    }
  }
  const layout=window.BASAIR_PAGE_LINES?.[page]||[];let html='';
  const rows=layout.length?Math.max(...layout.map(row=>row[0])):15;
  const renderWords=(words,line,centered=false)=>{
    if(!words.length)return;
    html+=`<div class="mushaf-line${centered?' centered':''}" style="grid-row:${line};font-family:${useGlyphs?`'${font}'`:'UthmanicHafs,AmiriQuran'}">`;
    for(const w of words){
      const end=w.char_type_name==='end',qcf=useGlyphs,text=qcf?(w.code_v2||''):(w.text_qpc_hafs||w.text||'');
      html+=`<span class="word ${end?'end':''}" data-surah="${w.surah}" data-verse="${w.verse}" style="font-family:${qcf?`'${font}'`:'UthmanicHafs,AmiriQuran'}"><span class="${qcf?'qpc-glyph':''}">${text}</span>${end?marker(w.surah,w.verse):''}</span>`;
    }
    html+='</div>';
  };
  if(layout.length){
    for(const [line,type,centered,first,last,surah] of layout){
      if(type==='surah_name')html+=`<div class="cartouche" style="grid-row:${line}">سُورَةُ ${SURAH_NAMES[surah-1]}</div>`;
      else if(type==='basmallah')html+=`<div class="basmala" style="grid-row:${line}">بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ</div>`;
      else renderWords(fallbackLines.get(line)||[],line,Boolean(centered));
    }
  }else for(let line=1;line<=15;line++)renderWords(fallbackLines.get(line)||[],line);
  return{html,rows};
}
function setPageContent(body,content){body.style.gridTemplateRows=`repeat(${content.rows},minmax(0,1fr))`;body.innerHTML=content.html}
function renderQcf(data,font,useGlyphs=true){const surahs=[...new Set((data.verses||[]).map(v=>Number(String(v.verse_key).split(':')[0])))];if(!pageWithinSurah(state.surah,state.page)){state.surah=surahs[0]||state.surah;updateChrome()}setPageContent($('mushafBody'),pageHtml(data,font,useGlyphs));animateMushafBody();bindPage($('mushaf'));fitMushafLines();const first=data.verses[0];$('juzLabel').textContent=`الجزء ${toAr(first.juz_number||1)}`;$('hizbLabel').textContent=`الحزب ${toAr(Math.ceil(first.hizb_number||1))}`;$('surahLabel').textContent=surahs.map(s=>`سورة ${SURAH_NAMES[s-1]}`).join(' · ');$('footerSurah').textContent=surahs.map(s=>SURAH_NAMES[s-1]).join(' · ')}
function renderFatihaFallback(){const body=$('mushafBody');body.style.gridTemplateRows='repeat(10,minmax(0,1fr))';body.innerHTML='<div class="cartouche">سُورَةُ الْفَاتِحَةِ</div><div class="basmala"></div>'+FALLBACK_FATIHA.map((text,i)=>`<div class="mushaf-line"><span class="word end" data-surah="1" data-verse="${i+1}">${text} ۝${toAr(i+1)}${marker(1,i+1)}</span></div>`).join('');animateMushafBody();bindPage($('mushaf'));fitMushafLines();$('juzLabel').textContent='الجزء الأول';$('hizbLabel').textContent='الحزب الأول'}
function renderSecond(data,page,font,useGlyphs=true){const body=$('secondMushafBody'),surahs=[...new Set((data.verses||[]).map(v=>Number(String(v.verse_key).split(':')[0])))],first=data.verses[0];setPageContent(body,pageHtml(data,font,useGlyphs,page));animateMushafBody(body);bindPage($('mushafSecond'));$('secondJuzLabel').textContent=`الجزء ${toAr(first.juz_number||1)}`;$('secondHizbLabel').textContent=`الحزب ${toAr(Math.ceil(first.hizb_number||1))}`;$('secondSurahLabel').textContent=surahs.map(s=>`سورة ${SURAH_NAMES[s-1]}`).join(' · ');$('secondFooterSurah').textContent=surahs.map(s=>SURAH_NAMES[s-1]).join(' · ');$('secondPageNumber').textContent=toAr(page);$('mushafSecond').classList.toggle('opening-page',page<=2);fitMushafLines()}
async function loadSecondPage(){if(!spreadMode()||state.page>=604){$('secondMushafBody').innerHTML='';return}const page=state.page+1;$('secondMushafBody').innerHTML='<div class="status"><span class="spinner"></span></div>';try{const data=await fetchPage(page);renderSecond(data,page,'UthmanicHafs',false);try{renderSecond(data,page,await loadFont(page),true)}catch{}}catch{$('secondMushafBody').innerHTML='<div class="status">تعذر تحميل الصفحة المقابلة</div>'}}
async function loadPage(){updateChrome();state.verse=null;state.open=null;renderQuestions();$('mushafBody').innerHTML='<div class="status"><div><span class="spinner"></span>يُهيَّأ خط صفحة المصحف…</div></div>';const secondPromise=loadSecondPage();let data;try{data=await fetchPage(state.page)}catch{if(state.page===1)renderFatihaFallback();else{$('mushafBody').innerHTML='<div class="status"><div><strong>هذه الصفحة لم تُنزَّل بعد.</strong><br>اتصل بالإنترنت أو استخدم زر تنزيل المصحف للعمل دون اتصال.<br><button class="retry" id="retry">إعادة المحاولة</button></div></div>';setTimeout(()=>$('retry')?.addEventListener('click',loadPage),0)}await secondPromise;return}renderQcf(data,'UthmanicHafs',false);try{const font=await loadFont(state.page);renderQcf(data,font,true)}catch{toast('عُرض الخط العثماني الاحتياطي بأمان')}await secondPromise}

function renderQuestions(){if(!state.verse){$('panelTitle').textContent='المس آية من المصحف';$('questionCount').textContent='';$('questionList').innerHTML='<div class="empty empty-guide"><span class="empty-emblem">ب</span><strong>اختر آية من المصحف</strong><small>المس كلمات الآية أو رقمها الأخضر لتظهر بصائرها وأسئلتها البيانية.</small></div>';return}const all=questionsFor(state.surah,state.verse),term=$('search').value.trim(),items=all.filter(q=>!term||(q.question+' '+q.answer).includes(term));$('panelTitle').textContent=`سورة ${META[state.surah].name} · الآية ${toAr(state.verse)}`;$('questionCount').textContent=all.length?`${toAr(all.length)} ${all.length===1?'سؤال':'أسئلة'}`:'لا توجد أسئلة';$('questionList').innerHTML=items.length?items.map(q=>`<article class="question ${state.open===q.id?'open':''}" data-id="${q.id}"><button class="q-trigger"><span class="q-no">${toAr(q.number)}</span><span class="q-text">${esc(q.question)}</span><span>⌄</span></button><div class="q-body"><div class="q-inner"><div class="answer"><span class="label">الجواب</span>${esc(q.answer)}</div><div class="sources"><span class="label">المصادر</span>${sourcesHtml(q.sources)}</div></div></div></article>`).join(''):'<div class="empty empty-guide"><span class="empty-emblem quiet">◇</span><strong>لا توجد بصائر مرتبطة بهذه الآية حاليًا</strong><small>يمكنك اختيار آية أخرى أو متابعة القراءة.</small></div>';document.querySelectorAll('.q-trigger').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('.question').dataset.id;state.open=state.open===id?null:id;renderQuestions()}))}
function step(delta){state.page=Math.max(1,Math.min(604,state.page+delta*(spreadMode()?2:1)));loadPage();window.scrollTo({top:0,behavior:'smooth'})}
function closePanel(){$('panel').classList.remove('open');$('backdrop').classList.remove('open')}
function applyZoom(width=state.zoom){state.zoom=Math.max(580,Math.min(940,Number(width)||780));document.documentElement.style.setProperty('--reader-page-width',`${state.zoom}px`);$('zoomResetBtn').textContent=`${toAr(Math.round(state.zoom/780*100))}٪`;$('zoomOutBtn').disabled=state.zoom<=580;$('zoomInBtn').disabled=state.zoom>=940;localStorage.setItem('basair-page-width',state.zoom)}
function surahAtPage(page){let surah=1;for(let i=0;i<PAGE_STARTS.length;i++){if(PAGE_STARTS[i]<=page)surah=i+1;else break}return surah}
function populateNavigation(){$('navSurahSelect').innerHTML=SURAH_NAMES.map((name,i)=>`<option value="${i+1}">${toAr(i+1)} · سورة ${name}</option>`).join('');$('navJuzSelect').innerHTML=JUZ_PAGE_STARTS.map((page,i)=>`<option value="${i+1}">الجزء ${toAr(i+1)} · الصفحة ${toAr(page)}</option>`).join('')}
function openNavigation(){closeQuranSearch();$('pageNumberInput').value=state.page;$('pageRange').value=state.page;$('navSurahSelect').value=state.surah;const juz=JUZ_PAGE_STARTS.reduce((found,page,i)=>page<=state.page?i+1:found,1);$('navJuzSelect').value=juz;$('navOverlay').classList.add('open');$('navOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('pageNumberInput').focus(),50)}
function closeNavigation(){$('navOverlay').classList.remove('open');$('navOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function jumpToPage(page,preferredSurah=null){const target=Math.max(1,Math.min(604,Number(page)||1));closeNavigation();state.page=target;state.surah=preferredSurah||surahAtPage(target);await loadPage();window.scrollTo({top:0,behavior:'smooth'});toast(`الصفحة ${toAr(target)}`)}
function activateNavTab(name){document.querySelectorAll('[data-nav-tab]').forEach(button=>button.classList.toggle('active',button.dataset.navTab===name));document.querySelectorAll('[data-nav-pane]').forEach(pane=>pane.classList.toggle('active',pane.dataset.navPane===name))}
let touchStartX=0,touchStartY=0,touchStartTime=0;function enableSwipeNavigation(){const bindSwipe=(page,role)=>{page.addEventListener('touchstart',event=>{const touch=event.changedTouches[0];touchStartX=touch.clientX;touchStartY=touch.clientY;touchStartTime=Date.now()},{passive:true});page.addEventListener('touchend',event=>{const touch=event.changedTouches[0],dx=touch.clientX-touchStartX,dy=touch.clientY-touchStartY;if(Date.now()-touchStartTime>=900||Math.abs(dx)<=60||Math.abs(dx)<=Math.abs(dy)*1.25)return;if(spreadMode()&&((role==='first'&&dx>0)||(role==='second'&&dx<0)))return;suppressClickUntil=Date.now()+500;step(dx>0?1:-1)},{passive:true})};bindSwipe($('mushaf'),'first');bindSwipe($('mushafSecond'),'second')}
const COLOR_THEMES={madinah:'المدينة',night:'الليل',blue:'الصفاء',paper:'الورق',burgundy:'العنابي'};
function setColorTheme(theme,announce=false){if(!COLOR_THEMES[theme])theme='madinah';document.body.classList.remove('night','theme-madinah','theme-night','theme-blue','theme-paper','theme-burgundy');document.body.classList.add(`theme-${theme}`);if(theme==='night')document.body.classList.add('night');localStorage.setItem('basair-color-theme',theme);localStorage.setItem('basair-v3-theme',theme==='night'?'night':'light');document.querySelectorAll('[data-theme-choice]').forEach(button=>{const active=button.dataset.themeChoice===theme;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});$('themeBtn').title=`ألوان القراءة · ${COLOR_THEMES[theme]}`;if(announce)toast(`تم اختيار ألوان ${COLOR_THEMES[theme]}`)}
function openThemePicker(){closeQuranSearch();closeNavigation();$('themeOverlay').classList.add('open');$('themeOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeThemePicker(){$('themeOverlay').classList.remove('open');$('themeOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
let toastTimer;function toast(text,duration=1800){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),duration)}
async function downloadOfflinePack(){if(state.downloading)return;state.downloading=true;$('offlineBtn').disabled=true;try{if(navigator.storage?.persist)await navigator.storage.persist();await loadQpcData();for(let start=1;start<=604;start+=4){const pages=Array.from({length:Math.min(4,605-start)},(_,i)=>start+i);$('offlineBtn').textContent=`تنزيل ${toAr(Math.min(604,start+3))}/${toAr(604)}`;await Promise.all(pages.map(async page=>{await fetchPage(page);await getFontBytes(page)}));for(const page of pages)if(page!==state.page){pageMemory.delete(page);fontMemory.delete(page)}}$('offlineBtn').textContent='متاح دون اتصال ✓';localStorage.setItem('basair-offline-complete-v5','yes');toast('اكتمل تنزيل المصحف للعمل دون اتصال',3200)}catch(error){$('offlineBtn').textContent='استكمال التنزيل';toast('توقف التنزيل؛ يمكنك استكماله عند عودة الاتصال',3200)}finally{state.downloading=false;$('offlineBtn').disabled=false}}

let deferredInstallPrompt=null;
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isAppleMobile(){return /iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function refreshInstallState(){const installed=isStandalone();document.body.classList.toggle('standalone',installed);$('installBtn').hidden=installed}
function closeInstallHelp(){$('installOverlay').classList.remove('open');$('installOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openInstallHelp(){closeQuranSearch();closeNavigation();closeThemePicker();const local=location.protocol==='file:',apple=isAppleMobile();let steps,action='حسنًا';if(local){$('installIntro').textContent='التثبيت يحتاج إلى فتح النسخة من رابط ويب آمن بعد نشرها، أما هذا الملف المحلي فيبقى صالحًا للمعاينة.';steps=['انشر حزمة المشروع على رابط HTTPS.','افتح الرابط المنشور في Safari أو Chrome.','اضغط زر «تثبيت» داخل بصائر.']}else if(apple){$('installIntro').textContent='يمكنك إضافة بصائر إلى شاشة iPhone أو iPad ليعمل كتطبيق مستقل.';steps=['افتح هذه الصفحة في متصفح Safari.','اضغط زر المشاركة في شريط Safari.','اختر «إضافة إلى الشاشة الرئيسية»، ثم اضغط «إضافة».']}else if(deferredInstallPrompt){$('installIntro').textContent='أصبح بصائر جاهزًا للتثبيت كتطبيق مستقل على جهازك.';steps=['اضغط الزر أدناه.','وافق على رسالة التثبيت.','افتح بصائر من الشاشة الرئيسية.'];action='تثبيت الآن'}else{$('installIntro').textContent='يمكنك تثبيت بصائر من قائمة المتصفح بعد فتح الرابط المنشور.';steps=['افتح قائمة المتصفح ⋮.','اختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».','افتح بصائر من الأيقونة الجديدة.']}$('installSteps').innerHTML=steps.map(step=>`<li>${step}</li>`).join('');$('installActionBtn').textContent=action;$('installOverlay').classList.add('open');$('installOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
async function requestInstall(){if(!deferredInstallPrompt){openInstallHelp();return}deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;if(choice.outcome==='accepted')toast('جارٍ تثبيت بصائر…',2600);deferredInstallPrompt=null;refreshInstallState();closeInstallHelp()}
function closeAbout(){$('aboutOverlay').classList.remove('open');$('aboutOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openAbout(){closeQuranSearch();closeNavigation();closeThemePicker();closeInstallHelp();$('aboutOverlay').classList.add('open');$('aboutOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}

$('surahSelect').addEventListener('change',e=>{state.surah=Number(e.target.value);state.page=META[state.surah].pages[0];loadPage()});$('prevPage').addEventListener('click',()=>step(-1));$('nextPage').addEventListener('click',()=>step(1));$('search').addEventListener('input',renderQuestions);$('closePanel').addEventListener('click',closePanel);$('backdrop').addEventListener('click',closePanel);$('offlineBtn').addEventListener('click',downloadOfflinePack);$('markersBtn').addEventListener('click',()=>{state.markers=!state.markers;localStorage.setItem('basair-v3-markers',state.markers?'on':'off');updateChrome();toast(state.markers?'ظهرت أرقام الأسئلة':'وضع القراءة الصافية')});
$("quranSearchBtn").addEventListener('click',openQuranSearch);$('closeQuranSearch').addEventListener('click',closeQuranSearch);$('quranSearchOverlay').addEventListener('click',e=>{if(e.target===$('quranSearchOverlay'))closeQuranSearch()});$('clearQuranSearch').addEventListener('click',()=>{$('quranSearchInput').value='';performQuranSearch();$('quranSearchInput').focus()});$('quranSearchInput').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(performQuranSearch,320)});
$('pageJumpBtn').addEventListener('click',openNavigation);$('edgePrev').addEventListener('click',()=>step(-1));$('edgeNext').addEventListener('click',()=>step(1));$('edgeNextSecond').addEventListener('click',()=>step(1));$('closeNav').addEventListener('click',closeNavigation);$('navOverlay').addEventListener('click',e=>{if(e.target===$('navOverlay'))closeNavigation()});document.querySelectorAll('[data-nav-tab]').forEach(button=>button.addEventListener('click',()=>activateNavTab(button.dataset.navTab)));$('pageRange').addEventListener('input',e=>$('pageNumberInput').value=e.target.value);$('pageNumberInput').addEventListener('input',e=>{$('pageRange').value=Math.max(1,Math.min(604,Number(e.target.value)||1))});$('pageNumberInput').addEventListener('keydown',e=>{if(e.key==='Enter')jumpToPage(e.target.value)});$('goPageBtn').addEventListener('click',()=>jumpToPage($('pageNumberInput').value));$('goSurahBtn').addEventListener('click',()=>{const surah=Number($('navSurahSelect').value);jumpToPage(META[surah].pages[0],surah)});$('goJuzBtn').addEventListener('click',()=>jumpToPage(JUZ_PAGE_STARTS[Number($('navJuzSelect').value)-1]));
$('zoomOutBtn').addEventListener('click',()=>applyZoom(state.zoom-40));$('zoomInBtn').addEventListener('click',()=>applyZoom(state.zoom+40));$('zoomResetBtn').addEventListener('click',()=>applyZoom(780));
$('themeBtn').addEventListener('click',openThemePicker);$('closeTheme').addEventListener('click',closeThemePicker);$('themeOverlay').addEventListener('click',e=>{if(e.target===$('themeOverlay'))closeThemePicker()});document.querySelectorAll('[data-theme-choice]').forEach(button=>button.addEventListener('click',()=>{setColorTheme(button.dataset.themeChoice,true);closeThemePicker()}));
$('installBtn').addEventListener('click',()=>deferredInstallPrompt?requestInstall():openInstallHelp());$('closeInstall').addEventListener('click',closeInstallHelp);$('installOverlay').addEventListener('click',e=>{if(e.target===$('installOverlay'))closeInstallHelp()});$('installActionBtn').addEventListener('click',()=>deferredInstallPrompt?requestInstall():closeInstallHelp());window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;refreshInstallState()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;refreshInstallState();closeInstallHelp();toast('تم تثبيت بصائر بنجاح',3000)});window.matchMedia('(display-mode: standalone)').addEventListener?.('change',refreshInstallState);spreadQuery.addEventListener?.('change',()=>{state.page=spreadStart(state.page);loadPage()});window.addEventListener('resize',()=>{clearTimeout(lineFitResizeTimer);lineFitResizeTimer=setTimeout(fitMushafLines,120)});
$('aboutBtn').addEventListener('click',openAbout);$('closeAbout').addEventListener('click',closeAbout);$('aboutAction').addEventListener('click',closeAbout);$('aboutOverlay').addEventListener('click',e=>{if(e.target===$('aboutOverlay'))closeAbout()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('aboutOverlay').classList.contains('open'))closeAbout();else if($('installOverlay').classList.contains('open'))closeInstallHelp();else if($('themeOverlay').classList.contains('open'))closeThemePicker();else if($('navOverlay').classList.contains('open'))closeNavigation();else if($('quranSearchOverlay').classList.contains('open'))closeQuranSearch();else closePanel()}if(!$('aboutOverlay').classList.contains('open')&&!$('installOverlay').classList.contains('open')&&!$('themeOverlay').classList.contains('open')&&!$('quranSearchOverlay').classList.contains('open')&&!$('navOverlay').classList.contains('open')){if(e.key==='ArrowLeft')step(1);if(e.key==='ArrowRight')step(-1)}});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});populateSurahs();populateNavigation();enableSwipeNavigation();applyZoom();setColorTheme(localStorage.getItem('basair-color-theme')||(localStorage.getItem('basair-v3-theme')==='night'?'night':'madinah'));refreshInstallState();if(localStorage.getItem('basair-offline-complete-v5')==='yes')$('offlineBtn').textContent='متاح دون اتصال ✓';loadPage();
